export const idRouter = Object.freeze({
	home: "/",
	about: "/about",
	contact: "/contact",
	service: "/services",
	solution: "/solution&product",
	career: "/career",
	blog: "/blog",
	demo: "/demo",
	vision: "/vision",
	login: "/login",
	careerDetail: "/career/:id",
	admin: "/admin",
	adminDashboard: "dashboard",
	adminInbox: "inbox",
	adminCalendar: "calendar",
	adminCareers: "careers",
	adminContact: "contact",
	adminSettings: "settings",
	solution_check: "/solution",
});
